### ISSUE TITLE
ShapeSource TODO checklist

### ISSUE THREAD

**Issue by RyanTG** [pinballmap/pbm-react#521]
- [x] Sort locations in order to manage marker order. Possibly using symbolZOrder? All icons must have a different z-order, and currently setting that by num_machines isn't suitable because so many locations have the same num_machines.
- [x] Show a different icon for Saved locations.
- [x] Selected icon behavior. And clean up selection code (is the sleep/loading stuff still needed for iOS?).
- [x] Location name label placement is currently not right. Two issues: `textVariableAnchor` does not currently work in rnmapbox (current best open is to pick a single anchor point for all labels); and when you zoom in and all labels start showing, the 10+ labels don't have "priority" and can be hidden if there are collisions (would be great to somehow prioritize those...).
- [x] Icon design-wise: might revise. Right now locations with <10 have a narrower icon. Might make more variations, like a lighter one for places with 1 machine (currently those have more opacity).
- [ ] Consider showing location type icon inside the icon. This might be a lot of work to pull off, and might look bad.

Will edit this as I think of more.
